import path from 'node:path';

import { defineConfig } from 'vitest/config';

export default defineConfig({
  resolve: {
    alias: {
      // The real module is generated by the esbuild build (scripts/build-support.mjs).
      'virtual:editor-worker-source': path.resolve(process.cwd(), 'tests/stubs/editorWorkerSource.ts'),
    },
  },
  test: {
    // jsdom for the DOM-building modules (thread cards, bridge globals). Monaco itself is
    // never booted in tests — it needs a real layout engine and web workers.
    environment: 'jsdom',
    include: ['tests/**/*.test.ts'],
    globals: false,
    restoreMocks: true,
  },
});
